title: '#EvdeKal'
email: sistem@baum.omu.edu.tr
description: >-
  Ondokuz Mayıs Üniversitesi Uzaktan Eğitim Merkezi Classroom Kılavuzu
url: "https://evdekal.omu.edu.tr"
permalink: pretty

# Build settings
markdown: kramdown
theme: bulma-clean-theme
remote_theme: chrisrhymes/bulma-clean-theme
plugins:
  - jekyll-feed
  - jekyll-seo-tag
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md
  - CNAME
